# Фреймворк PyTorch для разработки искусственных нейронных сетей
## Урок 1. Основные понятия и структуры PyTorch

### Добиться вразумительного результата от модели, собранной на занятии (7 угаданныx картинок из 10 предложенных на семинаре). Варианты изменений:
- изменение слоёв и их количества;
- изменение метода оптимизации; 
- изменение процесса обучения; 
- для продвинутых: преобразование данных transform


#### From The Lesson

In [ ]:
import torch
import torchvision
import numpy as np
from torch.autograd import Variable
from torch import nn 
from torch import optim

In [ ]:
linear = nn.Linear(2, 2)

In [ ]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.3067, -0.4802],
        [ 0.3126,  0.0786]], requires_grad=True)
b:  Parameter containing:
tensor([-0.3066, -0.4336], requires_grad=True)


Прекращение выполнения данного задания, в следствии отсутствия на уроке действий, которые можно определить как "7 угаданныx картинок".

#### Задание из файла HW_01.ipynb

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.randn(3, 4, 5).type(torch.float32)
x

tensor([[[ 0.3353,  1.6116,  0.7854,  1.0965,  0.4945],
         [ 2.2048,  0.3716,  0.5328, -0.1841, -0.7007],
         [-0.5627, -1.7811,  0.3305,  1.2759, -0.3821],
         [-1.6512,  0.9019,  0.8251,  0.2540, -0.9163]],

        [[-1.4070,  0.3543,  0.3562, -0.3759,  1.3574],
         [ 0.0927, -0.9614,  0.3123,  0.9419, -2.5078],
         [-0.5391, -0.8937, -0.1808,  0.9070,  0.4713],
         [ 0.1416, -2.0407,  1.9068,  0.4564,  0.6004]],

        [[ 0.6747, -0.0563,  1.3144, -0.5323,  1.3192],
         [ 0.0874, -0.7811,  0.9929, -0.1988, -1.3312],
         [ 0.3021,  0.8500,  1.1976, -0.3983, -0.0746],
         [-0.0504,  0.5778, -1.6703, -0.8573,  0.1133]]])

In [ ]:
# Выведите его форму (shape)
x.size()

torch.Size([3, 4, 5])

In [ ]:
# Приведите его к форме 6 X 10
x_reshaped = x.reshape(6,10)
x_reshaped

tensor([[ 0.3353,  1.6116,  0.7854,  1.0965,  0.4945,  2.2048,  0.3716,  0.5328,
         -0.1841, -0.7007],
        [-0.5627, -1.7811,  0.3305,  1.2759, -0.3821, -1.6512,  0.9019,  0.8251,
          0.2540, -0.9163],
        [-1.4070,  0.3543,  0.3562, -0.3759,  1.3574,  0.0927, -0.9614,  0.3123,
          0.9419, -2.5078],
        [-0.5391, -0.8937, -0.1808,  0.9070,  0.4713,  0.1416, -2.0407,  1.9068,
          0.4564,  0.6004],
        [ 0.6747, -0.0563,  1.3144, -0.5323,  1.3192,  0.0874, -0.7811,  0.9929,
         -0.1988, -1.3312],
        [ 0.3021,  0.8500,  1.1976, -0.3983, -0.0746, -0.0504,  0.5778, -1.6703,
         -0.8573,  0.1133]])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
m = torch.addcmul(torch.zeros(3,4,5), x, torch.FloatTensor([1, 4, 2, 2, 1]))
m

tensor([[[ 0.3353,  6.4462,  1.5707,  2.1931,  0.4945],
         [ 2.2048,  1.4864,  1.0656, -0.3683, -0.7007],
         [-0.5627, -7.1243,  0.6610,  2.5519, -0.3821],
         [-1.6512,  3.6076,  1.6501,  0.5080, -0.9163]],

        [[-1.4070,  1.4172,  0.7124, -0.7518,  1.3574],
         [ 0.0927, -3.8455,  0.6245,  1.8838, -2.5078],
         [-0.5391, -3.5750, -0.3617,  1.8140,  0.4713],
         [ 0.1416, -8.1626,  3.8136,  0.9128,  0.6004]],

        [[ 0.6747, -0.2251,  2.6288, -1.0645,  1.3192],
         [ 0.0874, -3.1246,  1.9857, -0.3975, -1.3312],
         [ 0.3021,  3.4001,  2.3952, -0.7966, -0.0746],
         [-0.0504,  2.3111, -3.3406, -1.7146,  0.1133]]])

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
mm = torch.mm(x_reshaped, x.reshape(10,6))
mm

tensor([[ 0.7629,  0.1771, -2.3384,  1.7679,  2.0776, -2.3209],
        [-0.7838, -0.1741, -0.3221,  1.2804,  1.3921,  3.0126],
        [ 3.8469, -4.3636, -3.2905,  2.4350,  2.9999, -6.9842],
        [ 6.7562, -8.0335,  0.1243, -0.7428, -1.9276,  0.6455],
        [ 5.2861,  1.5801, -0.3731,  0.5839,  2.2455,  0.5347],
        [-2.5749,  5.9971, -1.8690, -3.1692,  1.0860, -0.8668]])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = Variable(torch.FloatTensor([1]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]), requires_grad = True)

y = x**3 + z - 75*t

y

tensor([-148.5000], grad_fn=<SubBackward0>)

In [ ]:
y_back = y.backward()

print("До конца не понял механизм backward(): ", y_back)
print("Частнaя производная по х: ", x.grad)
print("Частная производная по z: ", z.grad)
print("Частная производная по t: ", t.grad)

До конца не понял механизм backward():  None
Частнaя производная по х:  tensor([3.])
Частная производная по z:  tensor([1.])
Частная производная по t:  tensor([-75.])


In [ ]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy
x_numpy = x.numpy()
x_numpy

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

linear = nn.Linear(2, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

w:  Parameter containing:
tensor([[ 0.3117, -0.5017],
        [-0.3228,  0.5113]], requires_grad=True)
b:  Parameter containing:
tensor([0.2912, 0.4961], requires_grad=True)


In [ ]:
x = Variable(torch.randn(2), requires_grad = True)
w1 = linear.bias
pred = linear(x)
pred

tensor([0.5553, 0.2235], grad_fn=<AddBackward0>)

In [ ]:
y = x**w1 - 2*x**2 + 5
y, x

(tensor([4.9877,    nan], grad_fn=<AddBackward0>),
 tensor([ 0.6719, -0.1088], requires_grad=True))

In [ ]:
pred = linear(y)
pred

tensor([nan, nan], grad_fn=<AddBackward0>)

По задаче "возьмите функцию y = x^w1 - 2 * x^2 + 5; посчитайте" остались вопросы, потому что нет понимания, каковы должны быть подсчеты