# Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) нет, так как количество строк А не равно количеству столбцов B в обе стороны;  
б) нет (см.пункт а) дла А $\times$ B и да для В $\times$ A;  
в) да, так как в матрице А 8 строк и 3 столбца, а в матрице В 8 столбцов и 3 строки;  
г) да, так как обе матрицы квадратные с одинаковой размерностью.

In [1]:
import numpy as np
def trying(A,B):
    try:
        result_1 = np.dot(A,B)
    except:
        result_1 = 'NO'
    try:
        result_2 = np.dot(B,A)
    except:
        result_2 = 'NO'
    return (result_1, result_2)

In [2]:
A = np.random.rand(4,2)
B = np.random.rand(4,2)
trying(A,B)

('NO', 'NO')

In [3]:
A = np.random.rand(2,5)
B = np.random.rand(5,3)
trying(A,B)

(array([[1.12830248, 1.29780026, 1.86376828],
        [0.94792725, 1.43944115, 1.24660443]]),
 'NO')

In [4]:
A = np.random.rand(8,3)
B = np.random.rand(3,8)
trying(A,B)

(array([[0.98257909, 0.73148961, 0.79719231, 0.93075756, 0.91583082,
         0.46773653, 0.61066889, 0.77266235],
        [0.92957986, 0.84590724, 0.69262103, 0.83055035, 1.14208735,
         0.52885067, 0.86548998, 0.91008916],
        [0.77803546, 0.40559112, 0.78528745, 0.89297071, 0.62994382,
         0.24016127, 0.48421223, 0.37337744],
        [0.72683771, 0.53405171, 0.66715518, 0.77864221, 0.85527049,
         0.31311314, 0.72566591, 0.53127733],
        [0.98898012, 0.51741002, 0.99449093, 1.13098393, 0.79648906,
         0.30746435, 0.60754955, 0.47804091],
        [0.62632511, 0.33695609, 0.59695119, 0.67892832, 0.44665673,
         0.21122386, 0.28996495, 0.32607334],
        [0.33265954, 0.25869453, 0.34187611, 0.40145438, 0.52479096,
         0.13493975, 0.52132035, 0.24160985],
        [1.08387257, 0.54652232, 1.0686873 , 1.21151977, 0.76100437,
         0.33685515, 0.51418006, 0.5126621 ]]),
 array([[1.27585155, 1.40070983, 1.31397801],
        [1.31445884, 1.3608966 ,

In [5]:
A = np.random.rand(4,4)
B = np.random.rand(4,4)
trying(A,B)

(array([[0.30475756, 1.17005355, 0.80797261, 0.35404406],
        [0.30059805, 1.28523347, 0.69608681, 0.44507854],
        [0.49901814, 1.32179001, 0.99219494, 0.62827994],
        [0.48517862, 1.41419241, 1.16743482, 0.50414071]]),
 array([[1.00996744, 0.35772815, 0.43347764, 0.38495001],
        [1.11679812, 0.65184673, 0.60816381, 0.64783285],
        [1.43577661, 0.76077948, 0.82087783, 0.54749191],
        [1.98200133, 0.93750297, 1.1047886 , 0.60363469]]))

Выводы:
- допустил серьезные ошибки в процессе выполнения задания;
- пункт а) неверн с точки зрения формулировки, в результате проверки стало очевидно, что равняться должны столбцы первой матрицы и строки второй;
- в пункте б) ответ обратный моему, по причине пренебрежения повторением теоретическим материалом;
- пункт в) получил верное утверждение, что результат перемножения существует, но значимым цифрам опять было напутано, также не указаны размерности итоговых матриц (8х8 и 3х3);
- пунтк г) получил достаточное точное утверждение, но не указаны размерности (4х4 и 4х4);
- принято решение не корректировать неверные ответы выше, так как они отображают мой учебный процесс.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B =\begin{pmatrix}
1 + 4 & -2 - 1\\ 
3 + 0 & 0 + 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [6]:
A = np.array([[1,-2], [3,0]])
B = np.array([[4,-1], [0,5]])
A + B

array([[ 5, -3],
       [ 3,  5]])

$A * B =\begin{pmatrix}
1*4 + (-2)*0 & 1*(-1) + (-2)*5\\ 
3*4 + 0*0 & 3*(-1) + 0*(5)
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [7]:
np.dot(A,B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C = 3 * \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 * \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 * \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$


In [8]:
A = np.array([[1,7], [3,-6]])
B = np.array([[0,5], [2,-1]])
C = np.array([[2,-4], [1,1]])
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$
$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4*4 + 1*1 & 4*5 + 1*(-2) & 4*2 + 1*3\\ 
5*4 + (-2)*1 & 5*5 + (-2)*(-2) & 5*2 + (-2)*3\\ 
2*4 + 3*1 & 2*5 + 3*(-2) & 2*2 + 3*3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

In [9]:
A = np.array([[4,1], [5,-2], [2,3]])
A_T = A.T
np.dot(A,A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4*4 + 5*5 + 2*2 & 1*4 + (-2)*5 + 3*2\\ 
1*4 + (-2)*5 + 3*2 & 1*1 + (-2)*(-2) + 3*3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [10]:
np.dot(A_T,A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [11]:
def vector_multiplication(vector_1, vector_2):
    return sum([int(x * y) for x, y in zip(vector_1, vector_2)])
def vector_from_transposed(matrix, column):
    return [vector[column] for vector in matrix]
def matrix_multiplication(matrix_1, matrix_2):
    m1, m2 = len(matrix_1), len(matrix_2[0])
    if len(matrix_1[0]) != len(matrix_2):
        return None
    mul = [[0 for i in range(m2)] for j in range(m1)]
    for i in range(m1):
        for j in range(m2):
            mul[i][j] = vector_multiplication(matrix_1[i], vector_from_transposed(matrix_2, j))
    return mul

In [12]:
print(matrix_multiplication(A_T,A))

[[45, 0], [0, 14]]


# Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

a)
$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx * sinx - cosx * (-cosx) = sin^2x + cos^2x = 1$

In [13]:
from sympy import *
from sympy.matrices import Matrix
x = symbols('x')
M = Matrix([[sin(x),-cos(x)],[cos(x),sin(x)]])
M.det()

sin(x)**2 + cos(x)**2

б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4*5*9 + 2*0*1 + 3*0*0 - 3*5*0 - 9*0*2 - 4*0*1 = 180$

In [14]:
A = np.array([[4,2,3], [0,5,1], [0,0,9]])
np.linalg.det(A)

180.0

в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*5*9 + 7*2*6 + 3*4*8 - 3*5*7 - 9*2*4 - 1*8*6 = 45 + 84 + 96 - 105 - 72 - 48 = 0$

In [15]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

6.66133814775094e-16

Не понял в чем "подвох", так как проверил работу np.linalg.det на нескольких матрицах, после чего проверил свое решение онлайн.  
<img src="L2_t1_проверка numpy.png">
<img src="L2_t1_проверка онлайн.png">

In [16]:
round(np.linalg.det(A), 3)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A) * det(A) = 4 * 4 = 16$  
б) $det(A^{T}) = det(A) = 4$  
в) $det(2A) = det(A) * 2^n = 2^n * 4$, где n количество строк в матрице A

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = (-2)*(-14)*13 + (-3)*4*7 + (-3)*7*6 - (-3)*(-14)*(-3) - (-2)*7*6 - 13*4*7$  
  
$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = 364 - 84 - 126 + 126 + 84 - 364 = 0$

Нулевая детерминанта свидетельствует о вырожденности матрицы.

In [17]:
A = np.array([[-2,7,-3], [4,-14,6], [-3,7,13]])
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Для решения обеих подзадач буду использовать следующий алгоритм:  

1. Находим не равные нулю миноры второго порядка. Если все миноры второго порядка равны нулю, то ранг матрицы будет равен единице (r =1).  

2. Если существует хотя бы один минор второго порядка, не равный нулю, то составляем окаймляющие миноры третьего порядка. Если все окаймляющие миноры третьего порядка равны нулю, то ранг матрицы равен двум (r =2).  

3. Если хотя бы один из окаймляющих миноров третьего порядка не равен нулю, то составляем окаймляющие его миноры. Если все окаймляющие миноры четвёртого порядка равны нулю, то ранг матрицы равен трём (r =2).  

4. Продолжаем так, пока позволяет размер матрицы.

а)  
$\begin{vmatrix}
1 & 2\\ 
1 & 1
\end{vmatrix} = 1 - 2 = -1 \ne 0$  
  
$\begin{vmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\
2 & 3 & 4
\end{vmatrix} = 4 + 4 + 9 - 6 - 8 - 3 = 0$

Ответ: $r = 2$

In [18]:
A = np.array([[1,2,3], [1,1,1], [2,3,4]])
np.linalg.matrix_rank(A)

2

б)  
$\begin{vmatrix}
0 & 0\\ 
2 & 3
\end{vmatrix} = 3 - 2 = 1 \ne 0$  
  
$\begin{vmatrix}
0 & 0 & 2\\ 
0 & 0 & 4\\ 
2 & 3 & 5
\end{vmatrix} = 0$  

$\begin{vmatrix}
0 & 0 & 2\\ 
0 & 0 & 3\\ 
2 & 3 & 6
\end{vmatrix} = 0$  
  
$\begin{vmatrix}
0 & 0 & 1\\ 
0 & 0 & 3\\ 
2 & 3 & 6
\end{vmatrix} = 0$  

Ответ: $r = 2$

In [19]:
A = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
np.linalg.matrix_rank(A)

3

Скорее всего в выбранном алгоритме опечатка и ранг будет равен 3, так как миноры третьего порядка равны нулю.
Интересно было бы разобраться: почему сайт [function-x.ru](https://function-x.ru/matrix_rang_calculator.php) утверждает, что ранг равен 4?  
<img src="Исходная матрица.png">
<img src="Приведения к трапециевидной.png">